### PR TITLE
Timeout changes

### LINKED ISSUE #53: Rescuing timeouts when delivering to subscribers
As far as I can tell, should posting a new topic event to a subscriber fail due to a time out, Faraday will throw an error that won't get caught. 

```
    # send data
    response = _conn.post do |post|
      post.headers['Content-Type'] = 'application/json'
      post.body = data.to_json
    end

    if response.success?
      _log.debug { "delivered #{@buffer.length} events to '#{@subscription.subscriber}'" }
      return true
    end

    _log.warn { "failed to deliver #{@buffer.length} events to '#{@subscription.subscriber}'" }
    raise CantDeliver.new('delivery failure')
```

I guess at this point that the message won't get ack'd, so it will ultimately be retried, but would it be better to rescue the Faraday error rather than let it raise?

//cc @mezis @pedrocunha

### PR DESCRIPTION
**Pull request by mrship**
:boom: Catch timeout errors so we can mark the delivery failure.
:clock1030: Allow timeout to be set by an ENV var
:white_check_mark: Closes #53 

//cc @pedrocunha, @mezis

### CODE REVIEW

File: routemaster/services/deliver.rb [hunk 1]
```diff
@@ -64,6 +69,11 @@ def _conn
     @_conn ||= Faraday.new(@subscription.callback) do |c|
       c.adapter Faraday.default_adapter
       c.basic_auth(@subscription.uuid, 'x')
+      if ENV.has_key?('DELIVERY_TIMEOUT')
+        c.options.timeout =
+          c.options.open_timeout =
```
Comment (pedrocunha) [inline routemaster/services/deliver.rb]: This is repeated isn't it ?

File: routemaster/services/deliver.rb [hunk 2]
```diff
@@ -64,6 +69,11 @@ def _conn
     @_conn ||= Faraday.new(@subscription.callback) do |c|
       c.adapter Faraday.default_adapter
       c.basic_auth(@subscription.uuid, 'x')
+      if ENV.has_key?('DELIVERY_TIMEOUT')
+        c.options.timeout =
```
Comment (pedrocunha) [inline routemaster/services/deliver.rb]: Maybe worth to have 2 ENV vars ? Or you think doesn't make much sense to fine tune this ?

**Comment by pedrocunha** [comment]
Looks good, one minor question

File: routemaster/services/deliver.rb (hunk 2 above)
Comment (mrship) [inline routemaster/services/deliver.rb]: I don't think it is worth fine tuning to that extent; we don't in [routemaster-drain](https://github.com/HouseTrip/routemaster-drain/blob/master/lib/routemaster/fetcher.rb#L51)

**Comment by pedrocunha** [comment]
:+1:
